### ISSUE TITLE
Failing to run google_search_features.js

### ISSUE THREAD

**Issue by osmestad** [GoogleChromeLabs/puppeteer-examples#18]
Very cool usages!

Unfortunately I'm having problems running the Google Search example, my output is:

```
oyvinds-mac:puppeteer-examples osmestad$ node google_search_features.js
Trace started.
Navigating to https://www.chromestatus.com/features
Waiting for page to be idle...
Trace complete.
(node:2259) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pid' of undefined
    at trace.traceEvents.filter.e (/Users/osmestad/Code/puppeteer-examples/google_search_features.js:195:38)
    at Array.filter (<anonymous>)
    at collectFeatureTraceEvents (/Users/osmestad/Code/puppeteer-examples/google_search_features.js:193:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'v tried with Node `v8.12.0` and `v10.13.0` any idea what might be causing this?

**Comment by osmestad** [comment]
If I revert Puppeteer to 1.7.0 it works :-) so I assume it is something that has changed between 1.7 and 1.8?

**Comment by RandomDude123** [comment]
I couldn't fix it by downgrading to 1.7.0 - still get the error from above

**Comment by mkamakura** [comment]
I also tried it. It works with v1.7.0 but does not work with v1.8.0.
It seems that `TracingStartedInPage` can not be found.
